#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
title: Wutan Bath

# Brief description of the site for SEO
tagline: Tai Chi and Kung Fu with the Bath branch of Wutan

# Name of the author
author: Wutan Bath

# Site description for SEO
description: Tai Chi and Kung Fu from the Wutan school in Bath, Bradford on Avon and Radstock

# Header text
header: "Control, discipline, flexibility, balance"

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/dragonphoenixbanner.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: david@bathtaichi.co.uk
  facebook: Wutanbath
  flickr:
  github: xanthipe/wutan-bath
  instagram: wutanbath
  linkedin:
  pinterest:
  rss: rss
  twitter: wutanbath
  stackoverflow:
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
  playconsole:
  mastodon: # <your-mastodon-instance>/@<your-user-name> eg. fosstodon.org/@username
  mailerlite: o5b1l1

twitter:
  username: wutanbath
  card: summary

facebook:
  publisher: Wutanbath

social:
  name: Wutan Bath
  links:
    - https://twitter.com/wutanbath
    - https://www.facebook.com/Wutanbath
    - https://instagram.com/wutanbath
    - https://github.com/xanthipe/wutan-bath

locale: en-GB

# Your website URL (e.g. http://amitmerchant1990.github.io or http://www.amitmerchant.com)
# Used for Sitemap.xml and your RSS feed
url: www.wutanbath.org.uk
enforce_ssl: https://www.wutanbath.org.uk

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v4.3.2

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: "highlight"

# Set the Sass partials directory, as we're using @imports
sass:
  style: compressed # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag
  - jekyll-paginate

include: ["_pages"]

paginate: 10
paginate_path: /page:num/

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - vendor
